"""Render the new chapter without executing or rewriting either earlier journey."""
from pathlib import Path
import ast
import re
import markdown

root = Path(__file__).resolve().parents[1]
tree = ast.parse((root / 'setup/build_journey_v1.py').read_text(encoding='utf-8'))
css = next(ast.literal_eval(n.value) for n in tree.body if isinstance(n, ast.Assign)
           and any(isinstance(t, ast.Name) and t.id == 'css' for t in n.targets))
css += '''
.report-frame{width:100%;height:780px;border:1px solid var(--line);background:white;border-radius:6px}.policy-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.policy-grid p{margin:8px 0}.policy-grid strong{display:block;font:30px Georgia,serif}.policy-grid small{display:block}.policy-track{height:10px;background:#476658;border-radius:5px}.policy-track span{display:block;height:100%;background:#edc09d;transition:width .2s}.mode-note{min-height:65px}@media(max-width:720px){.report-frame{height:640px}.policy-grid{gap:8px}.policy-grid strong{font-size:24px}}@media print{.report-frame{display:none}.policy-track{border:1px solid #777}}
'''
body = markdown.markdown((root / 'DEVELOPMENT-JOURNEY-V2.md').read_text(encoding='utf-8'),
                         extensions=['tables', 'toc', 'fenced_code'])
body = re.sub(r'^<h1[^>]*>.*?</h1>', '', body, count=1)
body = body.replace('<table>', '<div class="table-scroll" tabindex="0" role="region" aria-label="Scrollable evidence table"><table>').replace('</table>', '</table></div>')
body = body.replace('<!-- PRACTICE_CAPTURE -->', '''<figure class="demo"><img loading="lazy" src="docs/media/v2/practice-menu.png" alt="Actual Unity practice menu with Timing, Position, Fixed Benchmark and Mint adaptation controls"><figcaption>Fresh v0.5.1 Windows capture from an isolated synthetic input run. The practice choices occupy the left margin.</figcaption></figure>''')
body = body.replace('<!-- MAIN_MENU_CAPTURE -->', '''<figure class="demo"><img loading="lazy" src="docs/media/v2/main-menu.png" alt="Robo Open main menu displaying Mint Coach, Play Match, Practice and Learning, and Open Play Report"><figcaption>The actual current welcome screen. Practice &amp; Learning is visible beneath Play Match; the court remains visible.</figcaption></figure>''')
body = body.replace('<!-- REPORT_DEMO -->', '''<div class="demo"><p class="kicker">Interactive public example / synthetic observations</p><p><a href="docs/examples/play-report-v2.html" target="_blank" rel="noopener">Open the report in a full tab</a>. Scroll inside the report to try its court replay.</p><iframe class="report-frame" loading="lazy" title="Synthetic v0.5.1 Play Report with practice memory and court replay" src="docs/examples/play-report-v2.html"></iframe></div>''')
body = body.replace('<!-- POLICY_LAB -->', '''<div class="demo dark"><p class="kicker">Illustration / this does not train Mint</p><h3>Same abilities. A different mix of shots.</h3><div class="switches" role="group" aria-label="Illustrative Mint policy"><button data-policy="balanced" aria-pressed="true">Balanced</button><button data-policy="coach" aria-pressed="false">Coach example</button><button data-policy="competitive" aria-pressed="false">Competitive example</button><button data-policy="calibration" aria-pressed="false">Calibration</button></div><div class="policy-grid">''' + ''.join(f'<div><p>{name}<strong id="prob-{i}">33.3%</strong></p><div class="policy-track"><span id="bar-{i}" style="width:33.333%"></span></div></div>' for i,name in enumerate(['Left','Right','Lob'])) + '''</div><p class="mode-note" id="policy-note" aria-live="polite">Equal probabilities while evidence is insufficient. All three choices remain possible.</p><p class="caption">Hypothetical accepted preferences, not measured player data. Coach would favor the action supported as nearer its 70% return target; Competitive would favor the harder supported action. Promotion requires separate training and evaluation sessions. Every fourth match after promotion uses balanced calibration.</p></div>''')
nav = ''.join(f'<a href="#{ident}">{title}</a>' for ident, title in re.findall(r'<h2 id="([^"]+)">(.*?)</h2>', body))
js = '''
document.querySelector('#print').onclick=()=>window.print();
const examples={balanced:{p:[1/3,1/3,1/3],note:'Equal probabilities while evidence is insufficient. All three choices remain possible.'},coach:{p:[.2,.6,.2],note:'Illustration: evaluation supported right placement as closer to productive practice. The preferred shot gets 60%; the other two retain 20% each.'},competitive:{p:[.6,.2,.2],note:'Illustration: evaluation supported left placement as harder to return. Movement, reach and contact rules stay fixed.'},calibration:{p:[1/3,1/3,1/3],note:'Every fourth match after promotion gathers balanced evidence. The saved learned preference is retained for other matches.'}};
document.querySelectorAll('[data-policy]').forEach(b=>b.onclick=()=>{const x=examples[b.dataset.policy];document.querySelectorAll('[data-policy]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));x.p.forEach((p,i)=>{document.getElementById('prob-'+i).textContent=(100*p).toFixed(p===1/3?1:0)+'%';document.getElementById('bar-'+i).style.width=100*p+'%'});document.getElementById('policy-note').textContent=x.note});
const headings=[...document.querySelectorAll('main h2')],links=[...document.querySelectorAll('.side nav a')];const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)links.forEach(a=>{const active=a.getAttribute('href')==='#'+e.target.id;a.style.borderLeftColor=active?'#bc573a':'';if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})})},{rootMargin:'0px 0px -65% 0px'});headings.forEach(h=>observer.observe(h));
'''
page = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="How Robo Open gained persistent practice memory, drills, bounded Mint adaptation and a repaired HTML report viewer. Human decisions, failures, evidence and limits."><title>Robo Open v2 — Practice Memory and Learning</title><style>{css}</style></head><body><a class="skip" href="#journey">Skip to the journey</a><header class="mast"><span>ROBO OPEN / THIRD-ROUND FIELD NOTES</span><span><a href="JOURNEYS.html#v2" target="_top">Journey tabs</a> · <a href="DEVELOPMENT-JOURNEY-V2.md">Markdown source</a></span></header><section class="hero"><p class="kicker">v2 / Practice memory and learning</p><h1>A useful coach must<br>remember—and <em>show its evidence.</em></h1><p class="intro">From one missed return to a practice history. How human feedback led to repeatable drills, a cautiously adaptive opponent, and a report that finally opened.</p><figure><img src="docs/media/v2/main-menu.png" alt="Actual Robo Open Windows main menu showing the new Practice and Learning entry"><figcaption>Fresh v0.5.1 capture from an isolated validation run. Earlier journey chapters are preserved.</figcaption></figure></section><div class="versions"><span><b>v0.5.0</b> Memory + drills + adaptation</span><span><b>v0.5.1</b> Full HTML viewer repair</span><span><b>0</b> New Meshy credits used</span></div><div class="layout"><aside class="side"><p class="kicker">Read the full account</p><nav aria-label="Journey sections">{nav}</nav><button id="print">Print / save as PDF</button></aside><main id="journey">{body}</main></div><footer>Independent reconstruction inspired by <a href="https://www.youtube.com/watch?v=DQfL_l5lRpk">Chong-U’s video</a>. Public report data is synthetic. Private play records stay local. <a href="https://github.com/az9713/gpt-6-astra-tennis-game">Repository</a>.</footer><script>{js}</script></body></html>'''
(root / 'DEVELOPMENT-JOURNEY-V2.html').write_text(page, encoding='utf-8')
print(f'Rendered v2: {len(re.findall(r"<h2 ", body))} sections, {len(page)} characters')
