"""Create a portable, responsive gallery of the real Unity motion captures."""
from pathlib import Path
import markdown
from bs4 import BeautifulSoup
ROOT=Path(__file__).resolve().parents[1]
REPO='https://github.com/az9713/gpt-6-astra-tennis-game'
cards=[]
for name,title,note in [('forehand','Forehand','Load, rotate, strike, recover · contact 14/30'),('backhand','Backhand','Across-body preparation and follow-through · contact 15/30'),('smash','Automatic smash','Get beneath a high ball and swing · contact 25/30'),('serve','Serve / trophy','Toss, knee bend, trophy, extension · contact 42/30')]:
    poster='serve-trophy' if name=='serve' else name
    cards.append(f'<article><div class="card-head"><h2>{title}</h2><p>{note}</p></div><video controls muted loop playsinline preload="metadata" poster="docs/media/motion-{poster}.png" aria-label="{title} motion"><source src="docs/media/motion-{name}.mp4" type="video/mp4"></video></article>')
soup=BeautifulSoup(markdown.markdown((ROOT/'MOTION-UPGRADE.md').read_text(encoding='utf-8'),extensions=['tables','fenced_code']), 'html.parser')
soup.h1.decompose()
for a in soup.select('a[href]'):
    if not a['href'].startswith(('http','#')):a['href']=REPO+'/blob/main/'+a['href']
for table in soup.select('table'):table.wrap(soup.new_tag('div',attrs={'class':'table-scroll'}))
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Robo Open — The Motion Pass</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f0e7;color:#163932;font:17px/1.7 system-ui,Segoe UI,sans-serif}a{color:#236b5e;text-underline-offset:4px}.top{background:#163932;color:#f3f0e5;padding:24px 6vw;font-size:12px;letter-spacing:.12em;display:flex;justify-content:space-between;gap:20px}.top a{color:#e3eacb}.hero{padding:55px 6vw 45px;max-width:1350px;margin:auto}.eyebrow{color:#957047;font-size:12px;letter-spacing:.14em;font-weight:bold}h1{font:clamp(42px,6vw,80px)/1.05 Georgia,serif;letter-spacing:-.045em;max-width:850px;margin:20px 0 28px}h1 em{color:#b95b3e}.intro{max-width:810px;font-size:20px}.buttons{display:flex;flex-wrap:wrap;gap:12px;margin-top:25px}button,.download{font:14px system-ui;cursor:pointer;border:1px solid #9fb1a0;color:#163932;background:#e3e9d6;padding:12px 18px;border-radius:5px;text-decoration:none}.download{background:#163932;color:#f3f0e5}.gallery{display:grid;grid-template-columns:1fr 1fr;gap:25px;margin:0 auto;padding:0 5vw 50px;max-width:1500px}article{background:#163932;color:#f3f0e5;border-radius:7px;overflow:hidden}.card-head{padding:20px 25px}.card-head h2{font:30px Georgia,serif;margin:0}.card-head p{margin:8px 0 0;font-size:13px;color:#c2d4bf}video{display:block;width:100%;aspect-ratio:16/9;background:#0b2521}.note{max-width:1250px;padding:0 6vw;margin:0 auto 35px;font-size:14px;color:#596d60}.details{max-width:980px;margin:auto;padding:30px 6vw 70px}h2{font:34px Georgia,serif;margin-top:48px}h3{font:26px Georgia,serif}code{font:13px Consolas,monospace;background:#e4e8db;padding:2px 4px;overflow-wrap:anywhere}pre{overflow:auto;background:#e4e8db;padding:15px}.table-scroll{overflow:auto}table{border-collapse:collapse;font-size:14px}td,th{text-align:left;padding:13px;border-bottom:1px solid #c8d3c2;vertical-align:top}th{background:#dce4d0}li{margin:12px 0}footer{background:#163932;color:#d4dfc7;padding:30px 6vw;font-size:13px}footer a{color:#d4dfc7}:focus-visible{outline:3px solid #d38c58;outline-offset:4px}@media(max-width:760px){.gallery{grid-template-columns:1fr;padding:0 5vw 35px}.hero{padding-top:35px}.intro{font-size:18px}.details{padding:15px 6vw 40px}.top{font-size:10px}.card-head h2{font-size:27px}h2{font-size:30px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
</style></head><body><header class="top"><span>ROBO OPEN / VERSION 0.2</span><a href="DEVELOPMENT-JOURNEY.html">Full development journey</a></header><section class="hero"><span class="eyebrow">THE STRUCTURAL ANIMATION PASS</span><h1>Four strokes.<br><em>One swing key.</em></h1><p class="intro">Bent joints. Coordinated weight transfer. A real serve preparation. The same toy robots now prepare, strike and recover—and choose an overhead smash automatically when you swing at a suitable high ball.</p><div class="buttons"><button id="play">Play all four</button><button id="pause">Pause all</button><button id="speed" aria-pressed="false">Half speed</button><a class="download" href="'''+REPO+'''/releases/latest">Download Windows build</a></div></section><section class="gallery" aria-label="Four structural stroke animations">'''+''.join(cards)+'''</section><p class="note">Real Unity player captures, with actual joint guides shown in teal. The viewer displays full authored strokes; live gameplay uses anticipation and a shorter final swing window. No new Meshy generation was needed. In the downloaded motion viewer, B toggles guides and Escape closes it.</p><section class="details">'''+str(soup)+'''</section><footer><a href="DEVELOPMENT-JOURNEY.html">Original development journey</a> · <a href="'''+REPO+'''">Repository and source</a></footer><script>
const videos=[...document.querySelectorAll('video')];document.querySelector('#play').onclick=()=>videos.forEach(v=>{v.currentTime=0;v.play().catch(()=>{})});document.querySelector('#pause').onclick=()=>videos.forEach(v=>v.pause());document.querySelector('#speed').onclick=()=>{let button=document.querySelector('#speed'),slow=button.getAttribute('aria-pressed')!=='true';button.setAttribute('aria-pressed',String(slow));button.textContent=slow?'Normal speed':'Half speed';videos.forEach(v=>v.playbackRate=slow?.5:1)};
</script></body></html>'''
(ROOT/'MOTION-UPGRADE.html').write_text(page,encoding='utf-8')
print('Rendered motion gallery')
